# Generated by Django 3.1.7 on 2021-03-31 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='library.college'),
        ),
    ]
