# Generated by Django 3.1.7 on 2021-04-05 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210402_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='Issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='issue',
            name='Return_date',
            field=models.DateField(null=True),
        ),
    ]
