# Generated by Django 3.1.7 on 2021-04-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_points',
        ),
        migrations.AddField(
            model_name='student',
            name='membership',
            field=models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='wallet_points',
            field=models.IntegerField(null=True),
        ),
    ]
